// not enough of this to justify api (for now)

const cats = {
    "Shiro": {
        pic: "",
        personality: "Chill",
        attribution: "(not snowball)",
        rare: false,
    },
    "Tobi": {
        pic: "",
        personality: "Triumphant",
        attribution: "Ethan's cat",
        rare: false,
    },
    "Mocha": {
        pic: "",
        personality: "Sleepy",
        attribution: "Andy's cat",
        rare: false,
    },
    "Megumi": {
        pic: "",
        personality: "Depressed",
        attribution: "Gojo Catoru's son",
        rare: false,
    },
    "Guangdang": {
        pic: "",
        personality: "Sad",
        attribution: "@guangdang005",
        rare: false,
    },
    "Luna": {
        pic: "",
        personality: "Sus",
        attribution: "@monkeycatluna",
        rare: false,
    },
    "Kiko": {
        pic: "",
        personality: "Hungry",
        attribution: "Lilian's cat",
        rare: false,
    },
    "Sesame": {
        pic: "",
        personality: "Goofy",
        attribution: "Cody's cat",
        rare: false,
    },
    "Lola": {
        pic: "",
        personality: "Aesthetic",
        attribution: "Hannah's cat",
        rare: false,
    },
    "Comet": {
        pic: "",
        personality: "Grumpy",
        attribution: "Nicole Li's chonky cat",
        rare: true,
    },
    "Michi": {
        pic: "",
        personality: "Rowdy",
        attribution: "Gracie's suitemate's cat",
        rare: true,
    },
    "oye": {
        pic: "",
        personality: "oye",
        attribution: "oye",
        rare: true,
    },
    "Gojo Catoru": {
        pic: "",
        personality: "Strongest",
        attribution: "nah, i'd win", // more like a desc now
        rare: true,
    },
    "Sukatna": {
        pic: "",
        personality: "Strongest",
        attribution: "i'm not a fraud i swear",
        rare: true,
    },
}

const catAnimationDict = { // lmfao
    "Shiro": {
        "sitting": [
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/KD2oYxY.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
            "https://i.imgur.com/JXuCyGy.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/q1pWxRp.png",
            "https://i.imgur.com/JtMVQrG.png",
            "https://i.imgur.com/VdDGCZi.png",
            "https://i.imgur.com/GLy7sco.png",
            "https://i.imgur.com/lsn0Fip.png",
            "https://i.imgur.com/Lwrk2nI.png",
            "https://i.imgur.com/q1pWxRp.png",
            "https://i.imgur.com/JtMVQrG.png",
            "https://i.imgur.com/VdDGCZi.png",
            "https://i.imgur.com/GLy7sco.png",
            "https://i.imgur.com/lsn0Fip.png",
            "https://i.imgur.com/Lwrk2nI.png",
        ],
        "standing": [
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/QD9xCXE.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
            "https://i.imgur.com/wkDKr9O.png",
        ],
        "sleeping": [
            "https://i.imgur.com/aQFkVlJ.png",
            "https://i.imgur.com/x743VaG.png",
            "https://i.imgur.com/aQFkVlJ.png",
            "https://i.imgur.com/x743VaG.png",
            "https://i.imgur.com/aQFkVlJ.png",
            "https://i.imgur.com/x743VaG.png",
            "https://i.imgur.com/aQFkVlJ.png",
            "https://i.imgur.com/x743VaG.png",
            "https://i.imgur.com/aQFkVlJ.png",
            "https://i.imgur.com/x743VaG.png",
            "https://i.imgur.com/aQFkVlJ.png",
            "https://i.imgur.com/x743VaG.png",
        ],
        "sittingTrans": "https://i.imgur.com/bKGkRne.png",
        "sleepingTrans": "https://i.imgur.com/qptjWHs.png",
    },
    "Tobi": {
        "sitting": [
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/vpg2ciK.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
            "https://i.imgur.com/hR25AHy.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/SjOcfZq.png",
            "https://i.imgur.com/yu4SbRw.png",
            "https://i.imgur.com/JaK1ztJ.png",
            "https://i.imgur.com/T7fEaFl.png",
            "https://i.imgur.com/V2ShaW3.png",
            "https://i.imgur.com/ei3aLhb.png",
            "https://i.imgur.com/SjOcfZq.png",
            "https://i.imgur.com/yu4SbRw.png",
            "https://i.imgur.com/JaK1ztJ.png",
            "https://i.imgur.com/T7fEaFl.png",
            "https://i.imgur.com/V2ShaW3.png",
            "https://i.imgur.com/ei3aLhb.png",
        ],
        "standing": [
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/jwjwF1U.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
            "https://i.imgur.com/uuibtPI.png",
        ],
        "sleeping": [
            "https://i.imgur.com/mG2ERXW.png",
            "https://i.imgur.com/mVSriW8.png",
            "https://i.imgur.com/mG2ERXW.png",
            "https://i.imgur.com/mVSriW8.png",
            "https://i.imgur.com/mG2ERXW.png",
            "https://i.imgur.com/mVSriW8.png",
            "https://i.imgur.com/mG2ERXW.png",
            "https://i.imgur.com/mVSriW8.png",
            "https://i.imgur.com/mG2ERXW.png",
            "https://i.imgur.com/mVSriW8.png",
            "https://i.imgur.com/mG2ERXW.png",
            "https://i.imgur.com/mVSriW8.png",
        ],
        "sittingTrans": "https://i.imgur.com/lppqKIH.png",
        "sleepingTrans": "https://i.imgur.com/7g30KHF.png",
    },
    "Mocha": {
        "sitting": [
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/HJCNzmt.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
            "https://i.imgur.com/l2Ygd0n.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/RQAaliP.png",
            "https://i.imgur.com/QSYbdf6.png",
            "https://i.imgur.com/EfRdc9S.png",
            "https://i.imgur.com/PPGFQ11.png",
            "https://i.imgur.com/5W2FUBa.png",
            "https://i.imgur.com/1k41FGw.png",
            "https://i.imgur.com/RQAaliP.png",
            "https://i.imgur.com/QSYbdf6.png",
            "https://i.imgur.com/EfRdc9S.png",
            "https://i.imgur.com/PPGFQ11.png",
            "https://i.imgur.com/5W2FUBa.png",
            "https://i.imgur.com/1k41FGw.png",
        ],
        "standing": [
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
            "https://i.imgur.com/r6D9LC4.png",
        ],
        "sleeping": [
            "https://i.imgur.com/7XIZoED.png",
            "https://i.imgur.com/TEcBKn0.png",
            "https://i.imgur.com/7XIZoED.png",
            "https://i.imgur.com/TEcBKn0.png",
            "https://i.imgur.com/7XIZoED.png",
            "https://i.imgur.com/TEcBKn0.png",
            "https://i.imgur.com/7XIZoED.png",
            "https://i.imgur.com/TEcBKn0.png",
            "https://i.imgur.com/7XIZoED.png",
            "https://i.imgur.com/TEcBKn0.png",
            "https://i.imgur.com/7XIZoED.png",
            "https://i.imgur.com/TEcBKn0.png",
        ],
        "sittingTrans": "https://i.imgur.com/qiviFQL.png",
        "sleepingTrans": "https://i.imgur.com/t3JRizR.png",
    },
    "Megumi": {
        "sitting": [
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/Gdpulsl.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
            "https://i.imgur.com/DMrAVEb.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/z0Dbeyp.png",
            "https://i.imgur.com/1bUOwmV.png",
            "https://i.imgur.com/8CG1Kyd.png",
            "https://i.imgur.com/Uptb3av.png",
            "https://i.imgur.com/9H8I4s1.png",
            "https://i.imgur.com/ytMj1WJ.png",
            "https://i.imgur.com/z0Dbeyp.png",
            "https://i.imgur.com/1bUOwmV.png",
            "https://i.imgur.com/8CG1Kyd.png",
            "https://i.imgur.com/Uptb3av.png",
            "https://i.imgur.com/9H8I4s1.png",
            "https://i.imgur.com/ytMj1WJ.png",
        ],
        "standing": [
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/R3kt8l3.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
            "https://i.imgur.com/TE5m3LJ.png",
        ],
        "sleeping": [
            "https://i.imgur.com/Jlwul1E.png",
            "https://i.imgur.com/czfwFr6.png",
            "https://i.imgur.com/Jlwul1E.png",
            "https://i.imgur.com/czfwFr6.png",
            "https://i.imgur.com/Jlwul1E.png",
            "https://i.imgur.com/czfwFr6.png",
            "https://i.imgur.com/Jlwul1E.png",
            "https://i.imgur.com/czfwFr6.png",
            "https://i.imgur.com/Jlwul1E.png",
            "https://i.imgur.com/czfwFr6.png",
            "https://i.imgur.com/Jlwul1E.png",
            "https://i.imgur.com/czfwFr6.png",
        ],
        "sittingTrans": "https://i.imgur.com/hky5ERq.png",
        "sleepingTrans": "https://i.imgur.com/HLoRuk7.png",
    },
    "Guangdang": {
        "sitting": [
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/ssSIHHj.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
            "https://i.imgur.com/8aWzhIG.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/yiuyi7s.png",
            "https://i.imgur.com/OH6jvir.png",
            "https://i.imgur.com/NXKm3pi.png",
            "https://i.imgur.com/XAQO9BL.png",
            "https://i.imgur.com/yihF0KW.png",
            "https://i.imgur.com/8ZG4t8k.png",
        ],
        "standing": [
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/xekEu3e.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
            "https://i.imgur.com/e1QgIEo.png",
        ],
        "sleeping": [
            "https://i.imgur.com/qr9VI9I.png",
            "https://i.imgur.com/Sb4sNvW.png",
            "https://i.imgur.com/qr9VI9I.png",
            "https://i.imgur.com/Sb4sNvW.png",
            "https://i.imgur.com/qr9VI9I.png",
            "https://i.imgur.com/Sb4sNvW.png",
            "https://i.imgur.com/qr9VI9I.png",
            "https://i.imgur.com/Sb4sNvW.png",
            "https://i.imgur.com/qr9VI9I.png",
            "https://i.imgur.com/Sb4sNvW.png",
            "https://i.imgur.com/qr9VI9I.png",
            "https://i.imgur.com/Sb4sNvW.png",
        ],
        "sittingTrans": "https://i.imgur.com/Y5dAzea.png",
        "sleepingTrans": "https://i.imgur.com/J6n3NKo.png",
    },
    "Luna": {
        "sitting": [
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/MGoeHd5.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
            "https://i.imgur.com/38dpLsi.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/RvsLRqb.png",
            "https://i.imgur.com/gCa1hl7.png",
            "https://i.imgur.com/SdD78y6.png",
            "https://i.imgur.com/8ncopPP.png",
            "https://i.imgur.com/jFY9woT.png",
            "https://i.imgur.com/8ta1Rlq.png",
            "https://i.imgur.com/RvsLRqb.png",
            "https://i.imgur.com/gCa1hl7.png",
            "https://i.imgur.com/SdD78y6.png",
            "https://i.imgur.com/8ncopPP.png",
            "https://i.imgur.com/jFY9woT.png",
            "https://i.imgur.com/8ta1Rlq.png",
        ],
        "standing": [
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/dCuY76c.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
            "https://i.imgur.com/yVMpGXl.png",
        ],
        "sleeping": [
            "https://i.imgur.com/R4oiMXO.png",
            "https://i.imgur.com/OcREQ5Q.png",
            "https://i.imgur.com/R4oiMXO.png",
            "https://i.imgur.com/OcREQ5Q.png",
            "https://i.imgur.com/R4oiMXO.png",
            "https://i.imgur.com/OcREQ5Q.png",
            "https://i.imgur.com/R4oiMXO.png",
            "https://i.imgur.com/OcREQ5Q.png",
            "https://i.imgur.com/R4oiMXO.png",
            "https://i.imgur.com/OcREQ5Q.png",
            "https://i.imgur.com/R4oiMXO.png",
            "https://i.imgur.com/OcREQ5Q.png",
        ],
        "sittingTrans": "https://i.imgur.com/tlt98MU.png",
        "sleepingTrans": "https://i.imgur.com/5bvMytY.png",
    },
    "Kiko": {
        "sitting": [
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/7EV46JI.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",
            "https://i.imgur.com/BRYqG1W.png",

        ],
        "sittingPurring": [
            "https://i.imgur.com/wlwMpoA.png",
            "https://i.imgur.com/pGjK9Q5.png",
            "https://i.imgur.com/9shahbW.png",
            "https://i.imgur.com/STSwaFV.png",
            "https://i.imgur.com/M00cgSD.png",
            "https://i.imgur.com/lWK09cr.png",
            "https://i.imgur.com/wlwMpoA.png",
            "https://i.imgur.com/pGjK9Q5.png",
            "https://i.imgur.com/9shahbW.png",
            "https://i.imgur.com/STSwaFV.png",
            "https://i.imgur.com/M00cgSD.png",
            "https://i.imgur.com/lWK09cr.png",
        ],
        "standing": [
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
            "https://i.imgur.com/SQAtFGS.png",
        ],
        "sleeping": [
            "https://i.imgur.com/xI3YlrU.png",
            "https://i.imgur.com/oQ6h7VB.png",
            "https://i.imgur.com/xI3YlrU.png",
            "https://i.imgur.com/oQ6h7VB.png",
            "https://i.imgur.com/xI3YlrU.png",
            "https://i.imgur.com/oQ6h7VB.png",
            "https://i.imgur.com/xI3YlrU.png",
            "https://i.imgur.com/oQ6h7VB.png",
            "https://i.imgur.com/xI3YlrU.png",
            "https://i.imgur.com/oQ6h7VB.png",
            "https://i.imgur.com/xI3YlrU.png",
            "https://i.imgur.com/oQ6h7VB.png",
        ],
        "sittingTrans": "https://i.imgur.com/DlMwZ5k.png",
        "sleepingTrans": "https://i.imgur.com/ySgL4cj.png",
    },
    "Sesame": {
        "sitting": [
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/TSav744.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
            "https://i.imgur.com/okASkr9.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/ES5KamT.png",
            "https://i.imgur.com/TtSvXM0.png",
            "https://i.imgur.com/nvRFKCc.png",
            "https://i.imgur.com/XPpk8zw.png",
            "https://i.imgur.com/4MC098Z.png",
            "https://i.imgur.com/XDtCyLR.png",
            "https://i.imgur.com/ES5KamT.png",
            "https://i.imgur.com/TtSvXM0.png",
            "https://i.imgur.com/nvRFKCc.png",
            "https://i.imgur.com/XPpk8zw.png",
            "https://i.imgur.com/4MC098Z.png",
            "https://i.imgur.com/XDtCyLR.png",
        ],
        "standing": [
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/te5iXWM.png",
            "https://i.imgur.com/L4cbjtr.png",
            "https://i.imgur.com/te5iXWM.png",
        ],
        "sleeping": [
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
        ],
        "sittingTrans": "https://i.imgur.com/lWOtsYp.png",
        "sleepingTrans": "https://i.imgur.com/VsPpzzE.png",
    },
    "Lola": { // here fwd is j sesame
        "sitting": [
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/pqxiJ9Q.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
            "https://i.imgur.com/G0wytHa.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/bVesYAL.png",
            "https://i.imgur.com/ek16Pt6.png",
            "https://i.imgur.com/aERff5S.png",
            "https://i.imgur.com/YwuU8Fx.png",
            "https://i.imgur.com/hwq6P1y.png",
            "https://i.imgur.com/8jtJfez.png",
            "https://i.imgur.com/bVesYAL.png",
            "https://i.imgur.com/ek16Pt6.png",
            "https://i.imgur.com/aERff5S.png",
            "https://i.imgur.com/YwuU8Fx.png",
            "https://i.imgur.com/hwq6P1y.png",
            "https://i.imgur.com/8jtJfez.png",
        ],
        "standing": [
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/0oclYQr.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
            "https://i.imgur.com/RHPPROd.png",
        ],
        "sleeping": [
            "https://i.imgur.com/Ehti9DR.png",
            "https://i.imgur.com/0JBILzy.png",
            "https://i.imgur.com/Ehti9DR.png",
            "https://i.imgur.com/0JBILzy.png",
            "https://i.imgur.com/Ehti9DR.png",
            "https://i.imgur.com/0JBILzy.png",
            "https://i.imgur.com/Ehti9DR.png",
            "https://i.imgur.com/0JBILzy.png",
            "https://i.imgur.com/Ehti9DR.png",
            "https://i.imgur.com/0JBILzy.png",
            "https://i.imgur.com/Ehti9DR.png",
            "https://i.imgur.com/0JBILzy.png",

        ],
        "sittingTrans": "https://i.imgur.com/r7UBVrA.png",
        "sleepingTrans": "https://i.imgur.com/TvprbAI.png",
    },
    "Comet": {
        "sitting": [
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/62j3jPg.png",
            "https://i.imgur.com/rjljWke.png",
            "https://i.imgur.com/62j3jPg.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/WgWMqot.png",
            "https://i.imgur.com/0SAohc0.png",
            "https://i.imgur.com/ZZmSLb1.png",
            "https://i.imgur.com/f77vnzQ.png",
            "https://i.imgur.com/iMFJtWv.png",
            "https://i.imgur.com/FsdD5p9.png",
            "https://i.imgur.com/WgWMqot.png",
            "https://i.imgur.com/0SAohc0.png",
            "https://i.imgur.com/ZZmSLb1.png",
            "https://i.imgur.com/f77vnzQ.png",
            "https://i.imgur.com/iMFJtWv.png",
            "https://i.imgur.com/FsdD5p9.png",
        ],
        "standing": [
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/QlrNsuA.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
            "https://i.imgur.com/woOKPXR.png",
        ],
        "sleeping": [
            "https://i.imgur.com/nCPRjR9.png",
            "https://i.imgur.com/LLg8hST.png",
            "https://i.imgur.com/nCPRjR9.png",
            "https://i.imgur.com/LLg8hST.png",
            "https://i.imgur.com/nCPRjR9.png",
            "https://i.imgur.com/LLg8hST.png",
            "https://i.imgur.com/nCPRjR9.png",
            "https://i.imgur.com/LLg8hST.png",
            "https://i.imgur.com/nCPRjR9.png",
            "https://i.imgur.com/LLg8hST.png",
            "https://i.imgur.com/nCPRjR9.png",
            "https://i.imgur.com/LLg8hST.png",
        ],
        "sittingTrans": "https://i.imgur.com/TsvDniD.png",
        "sleepingTrans": "https://i.imgur.com/0RwSB1l.png",
    },
    "Michi": {
        "sitting": [
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/WDIMYwP.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
            "https://i.imgur.com/ecQEzzS.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/VjnpRKW.png",
            "https://i.imgur.com/hbkClvS.png",
            "https://i.imgur.com/rPBh3uf.png",
            "https://i.imgur.com/HdcftMY.png",
            "https://i.imgur.com/eA0lDd9.png",
            "https://i.imgur.com/0qcHJSi.png",
            "https://i.imgur.com/VjnpRKW.png",
            "https://i.imgur.com/hbkClvS.png",
            "https://i.imgur.com/rPBh3uf.png",
            "https://i.imgur.com/HdcftMY.png",
            "https://i.imgur.com/eA0lDd9.png",
            "https://i.imgur.com/0qcHJSi.png",
        ],
        "standing": [
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/1YNQFvx.png",
            "https://i.imgur.com/8I9G8Sm.png",
            "https://i.imgur.com/8I9G8Sm.png",
        ],
        "sleeping": [
            "https://i.imgur.com/VOm9ih2.png",
            "https://i.imgur.com/czAsVjy.png",
            "https://i.imgur.com/VOm9ih2.png",
            "https://i.imgur.com/czAsVjy.png",
            "https://i.imgur.com/VOm9ih2.png",
            "https://i.imgur.com/czAsVjy.png",
            "https://i.imgur.com/VOm9ih2.png",
            "https://i.imgur.com/czAsVjy.png",
            "https://i.imgur.com/VOm9ih2.png",
            "https://i.imgur.com/czAsVjy.png",
            "https://i.imgur.com/VOm9ih2.png",
            "https://i.imgur.com/czAsVjy.png",
        ],
        "sittingTrans": "https://i.imgur.com/4VzqVap.png",
        "sleepingTrans": "https://i.imgur.com/57SBZ4r.png",
    },
    "Gojo Catoru": {
        "sitting": [
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/gSygzbV.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
            "https://i.imgur.com/D9ExBZ6.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/VzLARbB.png",
            "https://i.imgur.com/5azYoPQ.png",
            "https://i.imgur.com/oKhC9vm.png",
            "https://i.imgur.com/ACRdqI1.png",
            "https://i.imgur.com/H39BEla.png",
            "https://i.imgur.com/Mo4ciZY.png",
            "https://i.imgur.com/VzLARbB.png",
            "https://i.imgur.com/5azYoPQ.png",
            "https://i.imgur.com/oKhC9vm.png",
            "https://i.imgur.com/ACRdqI1.png",
            "https://i.imgur.com/H39BEla.png",
            "https://i.imgur.com/Mo4ciZY.png",
        ],
        "standing": [
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/AwOL3yi.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
            "https://i.imgur.com/up1GOAV.png",
        ],
        "sleeping": [
            "https://i.imgur.com/Bs6lyiJ.png",
            "https://i.imgur.com/F88nUTk.png",
            "https://i.imgur.com/Bs6lyiJ.png",
            "https://i.imgur.com/F88nUTk.png",
            "https://i.imgur.com/Bs6lyiJ.png",
            "https://i.imgur.com/F88nUTk.png",
            "https://i.imgur.com/Bs6lyiJ.png",
            "https://i.imgur.com/F88nUTk.png",
            "https://i.imgur.com/Bs6lyiJ.png",
            "https://i.imgur.com/F88nUTk.png",
            "https://i.imgur.com/Bs6lyiJ.png",
            "https://i.imgur.com/F88nUTk.png",
        ],
        "sittingTrans": "https://i.imgur.com/IRpZKFL.png",
        "sleepingTrans": "https://i.imgur.com/LSevE6Y.png",
    },
    "Sukatna": {
        "sitting": [
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/7DfiT55.png",
            "https://i.imgur.com/aoDYWnn.png",
            "https://i.imgur.com/7DfiT55.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/7WlDaLl.png",
            "https://i.imgur.com/3oHHih2.png",
            "https://i.imgur.com/d7HlUrF.png",
            "https://i.imgur.com/5u63QXq.png",
            "https://i.imgur.com/NaTuSIp.png",
            "https://i.imgur.com/b8XhvD2.png",
            "https://i.imgur.com/7WlDaLl.png",
            "https://i.imgur.com/3oHHih2.png",
            "https://i.imgur.com/d7HlUrF.png",
            "https://i.imgur.com/5u63QXq.png",
            "https://i.imgur.com/NaTuSIp.png",
            "https://i.imgur.com/b8XhvD2.png",
        ],
        "standing": [
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
            "https://i.imgur.com/CDUdhll.png",
        ],
        "sleeping": [
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/HJBgDRs.png",
            "https://i.imgur.com/RJSa9MD.png",
            "https://i.imgur.com/Jdq0GHv.png",
            "https://i.imgur.com/RJSa9MD.png",
        ],
        "sittingTrans": "https://i.imgur.com/jKJQVXy.png",
        "sleepingTrans": "https://i.imgur.com/McwVXho.png",
    },
    "oye": {
        "sitting": [
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/IVUwmve.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
            "https://i.imgur.com/dza8gAk.png",
        ],
        "sittingPurring": [
            "https://i.imgur.com/YPhSORR.png",
            "https://i.imgur.com/tMILp8U.png",
            "https://i.imgur.com/lhNOEkL.png",
            "https://i.imgur.com/4HVdygS.png",
            "https://i.imgur.com/Oeiz2Gg.png",
            "https://i.imgur.com/8XOd18Y.png",
            "https://i.imgur.com/YPhSORR.png",
            "https://i.imgur.com/tMILp8U.png",
            "https://i.imgur.com/lhNOEkL.png",
            "https://i.imgur.com/4HVdygS.png",
            "https://i.imgur.com/Oeiz2Gg.png",
            "https://i.imgur.com/8XOd18Y.png",
        ],
        "standing": [
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
        ],
        "standingMeowing": [
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/csKo4h5.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
            "https://i.imgur.com/IXU4PgP.png",
        ],
        "sleeping": [
            "https://i.imgur.com/Avp5RX0.png",
            "https://i.imgur.com/sLgQh6q.png",
            "https://i.imgur.com/Avp5RX0.png",
            "https://i.imgur.com/sLgQh6q.png",
            "https://i.imgur.com/Avp5RX0.png",
            "https://i.imgur.com/sLgQh6q.png",
            "https://i.imgur.com/Avp5RX0.png",
            "https://i.imgur.com/sLgQh6q.png",
            "https://i.imgur.com/Avp5RX0.png",
            "https://i.imgur.com/sLgQh6q.png",
            "https://i.imgur.com/Avp5RX0.png",
            "https://i.imgur.com/sLgQh6q.png",
        ],
        "sittingTrans": "https://i.imgur.com/6klHceq.png",
        "sleepingTrans": "https://i.imgur.com/X4Z17M3.png",
    },
  };
  
  
  const achievements = [
    {
        name: "Feline Motivated",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Finish 1 task.",
        condition: {
            tasksCompleted: 1,
        }
    },
    {
        name: "Not Kitten",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Finish 5 tasks.",
        condition: {
            tasksCompleted: 5,
        }
    },
    {
        name: "Litter-ally Grinding",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Finish 20 tasks.",
        condition: {
            tasksCompleted: 20,
        }
    },
    {
        name: "Fur Real?",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Finish 50 tasks.",
        condition: {
            tasksCompleted: 50,
        }
    },
    {
        name: "Maximum Outpurrt",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Finish 100 tasks.",
        condition: {
            tasksCompleted: 100,
        }
    },
    {
        name: "Purrductive",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Finish 200 tasks.",
        condition: {
            tasksCompleted: 200,
        }
    },
    {
        name: "Paws-itively Awful",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Complete 5 sessions.",
        condition: {
            sessionsCompleted: 5,
        }
    },
    {
        name: "Cat-thartic Screaming",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Complete 10 sessions.",
        condition: {
            sessionsCompleted: 10,
        }
    },
    {
        name: "Cat-astrophe",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Complete 20 sessions.",
        condition: {
            sessionsCompleted: 20,
        }
    },
    {
        name: "I Hate This Fur-cking Place",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Complete 40 sessions.",
        condition: {
            sessionsCompleted: 40,
        }
    },
    {
        name: "Fur-midable Work Ethic",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Complete 80 sessions.",
        condition: {
            sessionsCompleted: 80,
        }
    },
    {
        name: "Stand purr-oud, you're strong",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Complete 120 sessions.",
        condition: {
            sessionsCompleted: 120,
        }
    },
    {
        name: "Nyani?",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Purchase 1 toy.",
        condition: {
            toysBought: 1,
        }
    },
    {
        name: "Hiss-terical",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Purchase 5 toys.",
        condition: {
            toysBought: 5,
        }
    },
    {
        name: "Meow and Fur-ever",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Purchase 10 toys.",
        condition: {
            toysBought: 10,
        }
    },
    {
        name: "I Have Truly Found Purr-adise",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Purchase 15 toys.",
        condition: {
            toysBought: 15,
        }
    },
    {
        name: "The Tuxedo Turns Up",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Attract Comet!",
        condition: {
        }
    },
    {
        name: "Michi",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Attract Michi!",
        condition: {
        }
    },
    {
        name: "oye.",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "attract oye",
        condition: {
        }
    },
    {
        name: "Nah, I'd win",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Attract Gojo Catoru!",
        condition: {

        }
    },
    {
        name: "Sukatna, King of Curses",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Attract Sukatna!",
        condition: {

        }
    },
    {
        name: "Battle of the Strongest",
        img: "https://cdn.discordapp.com/attachments/1152789674289528903/1200270172670394388/2Q.png?ex=65c591b5&is=65b31cb5&hm=249593700160cefea38b8de9caa7e838640aa33ca3762671eed2ee0cd1385ff0&",
        desc: "Attract both Gojo Catoru and Sukatna.",
        condition: {
        }
    },
];

const storeItems = [
    {
        name: "Yarn Ball",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "classic cat toy",
    },
    {
        name: "Boba",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "teado <3",
    },
    {
        name: "Laptop",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "psets for cats!",
    },
    {
        name: "Tim the Beaver",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "ihtfp",
    },
    {
        name: "Fish Plush",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by jessica!",
    },
    
    {
        name: "IKEA Bear", 
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by ethan!",
    }, 
    {
        name: "Butterfly Teaser",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by gracie!",
    }, // everything below should cost more
    {
        name: "Haku Plush",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by dom!",
    },
    {
        name: "Star Plush",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by vi!",
    },
    
    {
        name: "Tower of Tracks",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by alena!",
    },
    {
        name: "Blahaj", // blahaj
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by ethan!",
    },
    {
        name: "Lasagna",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by hao!",
    },
    {
        name: "Jenga", // jenga
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by vinh!",
    },
    {
        name: "Sushi Scratch Post",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by amy!",
    },
    {
        name: "Spaceship",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "created by jasmine!",
    },
    {
        name: "Apricity (Theme)",
        img: "https://cdn.discordapp.com/attachments/754243466241769515/1200940339775668305/yarn-ball-of-1.png",
        price: 1,
        attribution: "@apricityshortfilm",
    },

];
    
export { catAnimationDict, achievements, storeItems }